name: CI-Frontend

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and start backend container
        run: |
          docker pull ghcr.io/abramowichana/bags:0.0.1
          docker run -d -p 3001:3001 --name backend ghcr.io/abramowichana/bags:0.0.1

      - name: Wait for backend to be ready
        run: |
          for i in {1..30}; do
            if curl --silent --fail http://localhost:3001/health; then
              echo "Backend is up!"
              break
            fi
            echo "Waiting for backend..."
            sleep 2
          done

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start

      - name: Stop backend container
        if: always()
        run: docker stop backend && docker rm backend
